### ISSUE TITLE
Question about the step to update the GNN and the Graph Editor

### ISSUE THREAD

**Issue by jumxglhf** [qitianwu/GraphOOD-EERM#1]
Dear EERM authors,

Thanks for sharing the code of this project. I really enjoy reading the paper!

There might be one spot that I misunderstand in your implementation and it would be really helpful if you could explain this line of code.

https://github.com/qitianwu/GraphOOD-EERM/blob/ffdc4a11161976fac7dd71e2aa1dcd72db6e44e9/temp_arxiv/main.py#L104

My question lies in this line: shouldn't this line be ""m == args.T - 1"", as indicated in the Algorithm 1 in the paper.

I think the current implementation will not utilize the learned multiple environments (i.e., the parameter with shape K x N xN in the graph editor class) at all as the GNN will be updated before the graph editor does. And every time a new epoch starts the graph editors get reset.

Thanks in advance!

**Comment by qitianwu** [comment]
Hi Mingxuan,

Thank you for carefully checking the technical details. After double check, I think you are correct and the mentioned line should be "m == args.T - 1" to resolve the inconsistency for T>1. 

In our experiments, we found that the model is kind of sensitive to different setups for the graph editors which highly depends on the experimental datasets (given the diversity of our used datasets). Therefore, the value of T and whether to use reset for graph editors are differently used among different datasets. In some cases of our experiments (e.g., arxiv and cora), indeed, the graph editors were not optimized and can still yield competitive performance. The reason could be that the graph editors with random initialization can still augment the input data that explores the contexts and enable effective learning of the outer optimization (the main objective for ood generalization).

**Comment by jumxglhf** [comment]
Yes it looks like graph editors with random parameters still work. Thanks for the clarification!
